import time
from playwright.sync_api import sync_playwright

CHANNELS = [
    {
        "name": "TV3", 
        "slug": "tv3-live", 
        "group": "General", 
        "logo": "https://example.com/tv3.png"
    },
    {
        "name": "Drama Sangat", 
        "slug": "drama-sangat", 
        "group": "Series", 
        "logo": "https://example.com/drama-sangat.png"
    },
    {
        "name": "RTM TV1", 
        "slug": "rtm-tv1-live", 
        "group": "General", 
        "logo": "https://example.com/rtm1.png"
    },
    {
        "name": "Didik TV", 
        "slug": "didik-tv-live", 
        "group": "Education", 
        "logo": "https://example.com/didiktv.png"
    },
    {
        "name": "FIFA+", 
        "slug": "fifa-plus", 
        "group": "Sports", 
        "logo": "https://example.com/fifaplus.png"
    },
    {
        "name": "TV9 Malaysia", 
        "slug": "tv9-malaysia", 
        "group": "General", 
        "logo": "https://example.com/tv9.png"
    },
    {
        "name": "TV2", 
        "slug": "tv2-live", 
        "group": "General", 
        "logo": "https://example.com/tv2.png"
    },
    {
        "name": "Al Hijrah", 
        "slug": "al-hijrah", 
        "group": "Religious", 
        "logo": "https://example.com/alhijrah.png"
    },
    {
        "name": "Sukan RTM", 
        "slug": "sukan-rtm", 
        "group": "Sports", 
        "logo": "https://example.com/sukanrtm.png"
    },
    {
        "name": "Berita RTM", 
        "slug": "berita-waliyah", 
        "group": "News + Opinion", 
        "logo": "https://example.com/beritartm.png"
    },
    {
        "name": "Bernama", 
        "slug": "bernama", 
        "group": "News + Opinion", 
        "logo": "https://example.com/bernama.png"
    },
    {
        "name": "TV Okey", 
        "slug": "okey", 
        "group": "General", 
        "logo": "https://example.com/tvokey.png"
    }
]

def get_stream_url(slug):
    target_url = f"https://malaysia-tv.net/{slug}/"
    stream_url = ""
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36"
        )
        
        def handle_request(request):
            nonlocal stream_url
            if ".m3u8" in request.url:
                stream_url = request.url

        page.on("request", handle_request)
        
        try:
            page.goto(target_url, timeout=60000, wait_until="networkidle")
            if not stream_url:
                time.sleep(4)
        except Exception as e:
            print(f"Error retrieving {slug}: {e}")
        finally:
            browser.close()
            
    return stream_url

def update_m3u():
    # Menambahkan tag HTML redirect dan catatan hak cipta di awal file M3U
    m3u_content = """<!--more-->
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script language="javascript">
window.location.replace("https://sulthanpamenan.github.io/malaysia-tv-playlist/");
</script>
</head></html>

<=================== PLAYLIST AUTOGENERATED BY SUTAN PAMENAN ===================>
<=================== IF YOU FIND THIS PLAYLIST, PLEASE DO NOT SELL OR DISTRIBUTE IT FOR PERSONAL GAIN ===================>

#EXTM3U
"""
    
    user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36"
    headers_suffix = f"|User-Agent={user_agent}&Origin=https://malaysia-tv.net&Referer=https://malaysia-tv.net/"
    
    print(f"Processing {len(CHANNELS)} channels...")
    
    for ch in CHANNELS:
        group_title = ch.get("group", "Others")
        tv_logo = ch.get("logo", "")
        
        print(f"Processing: {ch['name']} [{group_title}] ({ch['slug']})...")
        url = get_stream_url(ch['slug'])
        if url:
            print(f"  -> Success: {url}")
            m3u_content += f'#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="{tv_logo}" group-title="{group_title}",{ch["name"]}\n'
            m3u_content += '#KODIPROP:inputstreamaddon=inputstream.adaptive\n'
            m3u_content += '#KODIPROP:inputstream.adaptive.manifest_type=hls\n'
            m3u_content += f'#KODIPROP:inputstream.adaptive.stream_headers=User-Agent={user_agent}&Origin=https://malaysia-tv.net&Referer=https://malaysia-tv.net/\n'
            m3u_content += f'{url}{headers_suffix}\n'
        else:
            print(f"  -> Failed to get the link for {ch['name']}")

    with open("playlist.m3u", "w", encoding="utf-8") as f:
        f.write(m3u_content)
    print("The M3U playlist has been successfully updated!")

if __name__ == "__main__":
    update_m3u()
